config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
	#名前は必須、かつ20文字以内
	validates :name , length: { maximum: 20 } , presence: true
	#内容は必須、かつ2文字以上30文字以下
	validates :body , length: { minimum: 2, maximum: 30 } , presence: true
	validates :age , numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 150 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  #（フィルタ機能）アクションの前後に任意の処理をできる→editアクション、updateアクションの前に処理できる
  before_action :set_message, only: [:edit, :update, :destroy]
  
  #メッセージを新規作成する際のフォームを表示するindexアクション
  def index
    #Messageモデルを初期化して@messageに代入→新規作成フォームが表示
    @message = Message.new
    #Messageを全て取得
    @messages = Message.all
  end
  
  #フォームからパラメータを受け取りDBに格納するcreateアクション
  def create
    #パラメータを受取り、Messageインスタンスを生成(Message.new)、@messageに代入
    @message = Message.new(message_params)
    #メッセージモデルのインスタンスをデータベースに保存
    if @message.save
      #メッセージが保存できたとき
      redirect_to root_path , notice: 'メッセージを保存しました。'
    else
      #メッセージが保存できなかったとき
      #→Message.allでテンプレートに使用するインスタンス変数を渡す
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました"
      render 'index'
    end
  end
  
  def edit
  end
  
  #エラーが※一番下ではエラー
  def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end
  
  def update
    if @message.update(message_params)
      #保存に成功した場合はトップページへリダイレクト
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      #保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  private
  def message_params
    params.require(:message).permit(:name, :body, :age)
  end
  
  def set_message
    #RESTという設計 → 求めるしリソースをURL内にあるid番号によって判断、要求されるリソースを特定できる設計
    #※params=フォームから送信したパラメータをコントローラ側に受け取るハッシュだけではない
    @message = Message.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Message Board</a>
      </div>
    </div>
  </nav>
  <div class="container">
    <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>
    
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<!--5-4フォームヘルパによってモデルオブジェクトとフォームを関連づけ
フォームで入力した値をモデルオブジェクトに割当てる-->
<!--引数@messageにMessagesControllerのindexアクションでMessage.newの代入する-->
<%= form_for(@message , html: {class: "form-horizontal"}) do |f| %>
	<% if @message.errors.present? %>
		<div class="alert alert-danger">
		  	<% alert %>
			<ul>
				<% @message.errors.full_messages.each do |full_message| %>
					<li>
						<%= full_message %>
					</li>
				<% end %>
			</ul>
		</div>
	<% end %>

<div class="form-horizontal">
	<div class="form-group">
		<label class="col-sm-1 control-label">名前:</label>
		<div class="col-sm-4"><%= f.text_field :name, :class => "form-control" %></div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-1 control-label">年齢:</label>
		<div class="col-sm-1"><%= f.text_field :age, :class => "form-control" %></div>
	</div>
	
	<div class="form-group">		
		<label class="col-sm-1 control-label">内容:</label>
		<div class="col-sm-11"><%= f.text_area :body, :class => "form-control" %></div>
	</div>
	
	<div class="col-sm-12 center-block form-group">
		<%= f.submit class: "btn btn-sm btn-primary col-sm-2 col-sm-offset-5" %>
	</div>
</div>
<% end %>

app/views/messages/edit.html.erb
<h1>メッセージ編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		メッセージ一覧
	</div>
	
	<div class="panel-body">	
		<!--インスタンス変数@messagesで★★★messageを繰り返す-->
		<% @messages.each do |message| %>
			<span class="label label-info"><%= message.name %></span> <!--名前-->
			<%= message.age %><!--年齢-->
			<%= message.body %> <!--内容-->
			<!--link_toメソッド ※link_toの第1引数→ラベル 、edit〜→編集ページのパス-->
			(<%= link_to "edit" , edit_message_path(message) %>
			<%= link_to "destroy" , message , method: :delete, data: { confirm: '削除してもいいですか？' } %>
			)
			<br>
		<% end %>
	</div>
</div>


<% #部分テンプレートを読み込んでいる %>
<%= render 'form' %>